# Generated by Django 2.1.3 on 2018-11-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_credential',
            new_name='UserCredentials',
        ),
    ]
